
services:
  database:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: database-service
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  backend:
    image: backend:1.0.0
    working_dir: /home/node/app
    restart: always
    build:
      context: ./backend
    container_name: backend-service
    ports:
      - 5000:5000
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    develop:
      watch:
        - action : rebuild
          path : ./backend/package.json
    depends_on:
      - database
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://database-service:27017/test
    networks:
      - mongo-network
      - backend-network
    command: [ "npm", "run", "dev" ]

  frontend:
    image: frontend:1.0.0
    working_dir: /home/node/app
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend-service:5000
    networks:
      - backend-network
    command: [ "npm", "run", "dev" ]

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge
  mongo-network:
    driver: bridge
