import {
	createApi,
	fetchBaseQuery,
	EndpointBuilder,
	BaseQueryFn,
} from "@reduxjs/toolkit/query/react";

import postApiEndPoints from "./posts";


// Create the API slice
export const api = createApi({
	reducerPath: "api",
	baseQuery: fetchBaseQuery({
		baseUrl: "https://jsonplaceholder.typicode.com",
	}),
	endpoints: (builder: EndpointBuilder<BaseQueryFn, string, string>) => ({
		...postApiEndPoints(builder),
	}),
});

// Export hooks generated by RTK Query
export const { useGetPostsQuery, useGetPostByIdQuery, useCreatePostMutation } = api;

export default api;
