#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Formating..."

# Run linters for frontend
cd frontend && npm run format && cd ..

# # Run linters for backend
# cd backend && npm run lint && cd ..

